version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/kavita"
      - "/komga"
      - "/nextcloud"
      - "/pigallery2"
      - "/prowlarr"
      - "/radarr"
      - "/sonarr"
    ignore:
      - dependency-name: library/mariadb
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "05:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 5
    labels:
      - "container-update"
